#!/usr/bin/env fish

# you can edit this file in ~/.local/bin/ folder 
#	echo "$Directory/$Name"
set Directory "/home/$USER/Pictures"
while true
	set Name (ls -1 -b -R ~/Pictures/|grep -i -e ".png" -e ".jpg" -e ".jpeg"|sort --random-sort|head -1)  
	sleep 60
	nitrogen --set-scaled $Directory/$Name 
end
